// const fs = require('fs')
const AuthenticationController = require('./controllers/main/AuthenticationController')
const isAuthenticated = require('./policies/isAuthenticated')
const RefPermissionTypeController = require('./controllers/ref/RefPermissionTypeController')
const UserController = require('./controllers/main/UserController')
const InquiryCivilController = require('./controllers/main/InquiryCivilController')
const CategoryController = require('./controllers/main/CategoryController')
const SlideController = require('./controllers/main/SlideController')
const LinksController = require('./controllers/main/LinksController')
const FaqsController = require('./controllers/main/FaqsController')
const RoleController = require('./controllers/main/RoleController')
const AddressController = require('./controllers/main/AddressController')
const LogController = require('./controllers/main/LogController')
const MenuController = require('./controllers/main/MenuController')
const SideMenuController = require('./controllers/main/SideMenuController')
const CommentController = require('./controllers/main/CommentController')
const SearchController = require('./controllers/main/SearchController')
const BannerController = require('./controllers/main/BannerController')
const CategoryCountController = require('./controllers/main/CategoryCountController')
const MenuCountController = require('./controllers/main/MenuCountController')
const ContentController = require('./controllers/main/ContentController')
const OnlineCountController = require('./controllers/main/OnlineCountController')
const RefBannerTypeController = require('./controllers/ref/RefBannerTypeController')
const RefAudioTypeController = require('./controllers/ref/RefAudioTypeController')
const webButtonController = require('./controllers/main/webButtonController')
const RefNewsTypeController = require('./controllers/ref/RefNewsTypeController')
const RefMenuTypeController = require('./controllers/ref/RefMenuTypeController')
const MenuViewTypeController = require('./controllers/ref/MenuViewTypeController')
const InquiryOrganizationController = require('./controllers/main/InquiryOrganizationController')
const DashboardController = require('./controllers/main/DashboardController')
const AttachmentController = require('./controllers/main/AttachmentController')
const RefStatusAndRespondController = require('./controllers/ref/RefStatusAndRespondController')
const path = require('path')
const uploadPath = path.join(__dirname.replace('src', ''), 'uploads')
var multer = require('multer')
var upload = multer({storage: multer.diskStorage({
  destination: function (req, file, callback) { callback(null, uploadPath) },
  filename: function (req, file, cb) {
    cb(null, Date.now() + file.originalname)
  }})
}).single('file')
module.exports = (app) => {
  // Гарын авлага зураг апплоад
  app.post('/file/upload', upload, function (req, res, next) {
    try {
      res.send({result: 'success', filename: req.file.filename})
    } catch (err) {
      res.status(500).send({error: err})
    }
  })
  // AttachmentController -> deleteOne
  app.put('/deleteOne', isAuthenticated, AttachmentController.deleteOne)
  // AuthenticationController
  app.post('/login', AuthenticationController.login)
  app.get('/user/info', isAuthenticated, AuthenticationController.show)
  app.put('/user/changePassword', isAuthenticated, AuthenticationController.changePassword)
  app.get('/user/logout', isAuthenticated, UserController.logout)
  // DashboardController
  app.get('/civilAndOrganizationPercent', DashboardController.civilAndOrganizationPercent)
  app.get('/civilAndOrganizationReply', DashboardController.civilAndOrganizationReply)
  app.get('/refSendBankLine', DashboardController.refSendBankLine)
  app.get('/refSendBankBar', DashboardController.refSendBankBar)
  // User
  app.get('/user/index', UserController.index)
  app.post('/user', UserController.post)
  // app.post('/user', isAuthenticated, UserController.post)
  app.put('/user/:itemId', UserController.put)
  // app.put('/user/:itemId', isAuthenticated, UserController.put)
  app.delete('/user/manyDelete', UserController.manyDestroy)
  app.put('/userManyDeActive', UserController.manyDeActive)
  app.put('/userManyRestore', UserController.manyRestore)
  app.put('/userChangePassword/:itemId', isAuthenticated, UserController.userChangePassword)
  // RefPermissionType
  app.get('/permissionType', RefPermissionTypeController.index)
  app.post('/permissionType', isAuthenticated, RefPermissionTypeController.post)
  app.put('/permissionType/:itemId', isAuthenticated, RefPermissionTypeController.put)
  app.delete('/permissionType/manyDelete', RefPermissionTypeController.manyDestroy)
  app.put('/permissionTypeManyDeActive', RefPermissionTypeController.manyDeActive)
  app.put('/permissionTypeManyRestore', RefPermissionTypeController.manyRestore)
  // InquiryCivilController
  app.get('/inquiryCivil/exportToExcel', isAuthenticated, InquiryCivilController.exportToExcel)
  app.get('/inquiryCivil/index', isAuthenticated, InquiryCivilController.index)
  app.post('/inquiryCivil/post', isAuthenticated, InquiryCivilController.post)
  app.put('/inquiryCivil/view/:itemId', isAuthenticated, InquiryCivilController.view)
  app.put('/inquiryCivil/update', isAuthenticated, InquiryCivilController.update)
  app.delete('/inquiryCivil/manyDelete', InquiryCivilController.manyDestroy)
  app.put('/inquiryCivilManyDeActive', InquiryCivilController.manyDeActive)
  app.put('/inquiryCivilManyRestore', InquiryCivilController.manyRestore)
  // Category
  app.get('/category/index', CategoryController.index)
  app.post('/category/post', CategoryController.post)
  app.put('/category/update', CategoryController.update)
  app.delete('/category/manyDelete', CategoryController.manyDestroy)
  // InquiryOrganizationController
  app.get('/inquiryOrganization/exportToExcel', isAuthenticated, InquiryOrganizationController.exportToExcel)
  app.get('/inquiryOrganization/index', isAuthenticated, InquiryOrganizationController.index)
  app.post('/inquiryOrganization/post', isAuthenticated, InquiryOrganizationController.post)
  app.put('/inquiryOrganization/view/:itemId', isAuthenticated, InquiryOrganizationController.view)
  app.put('/inquiryOrganization/update', isAuthenticated, InquiryOrganizationController.update)
  app.delete('/inquiryOrganization/manyDelete', InquiryOrganizationController.manyDestroy)
  app.put('/inquiryOrganizationManyDeActive', InquiryOrganizationController.manyDeActive)
  app.put('/inquiryOrganizationManyRestore', InquiryOrganizationController.manyRestore)
  // RefStatusAndRespondController
  app.get('/getRefStatus', RefStatusAndRespondController.getRefStatus)
  app.get('/getRefRespond', RefStatusAndRespondController.getRefRespond)
  // bannerType
  app.get('/bannerType/index', RefBannerTypeController.index)
  app.post('/bannerType/post', RefBannerTypeController.post)
  app.put('/bannerType/update', RefBannerTypeController.update)
  app.delete('/bannerType/manyDelete', RefBannerTypeController.manyDestroy)
  // audioType
  app.post('/audio/post', RefAudioTypeController.post)
  app.get('/audio/index', RefAudioTypeController.index)
  app.put('/audio/put', RefAudioTypeController.update)
  app.delete('/audio/manyDelete', RefAudioTypeController.manyDestroy)

  // menuViewType
  app.get('/menuViewType/index', MenuViewTypeController.index)
  // menuType
  app.get('/menuType/index', RefMenuTypeController.index)
  app.post('/menuType/post', RefMenuTypeController.post)
  app.put('/menuType/update', RefMenuTypeController.update)
  app.delete('/menuType/manyDelete', RefMenuTypeController.manyDestroy)
  // webButton
  app.get('/webButton/index', webButtonController.index)
  app.post('/webButton/post', webButtonController.post)
  app.put('/webButton/update', webButtonController.update)
  app.delete('/webButton/manyDelete', webButtonController.manyDestroy)
  // newsType
  app.get('/newsType/index', RefNewsTypeController.index)
  app.post('/newsType/post', RefNewsTypeController.post)
  app.put('/newsType/update', RefNewsTypeController.update)
  app.delete('/newsType/manyDelete', RefNewsTypeController.manyDestroy)
  // Banner
  app.get('/banner/index', BannerController.index)
  app.post('/banner/post', BannerController.post)
  app.put('/banner/update', BannerController.update)
  app.delete('/banner/manyDelete', BannerController.manyDestroy)
  // slide
  app.get('/slide/index', SlideController.index)
  app.post('/slide/post', SlideController.post)
  app.put('/slide/update', SlideController.update)
  app.delete('/slide/manyDelete', SlideController.manyDestroy)
  // links
  app.get('/links/index', LinksController.index)
  app.post('/links/post', LinksController.post)
  app.put('/links/update', LinksController.update)
  app.delete('/links/manyDelete', LinksController.manyDestroy)
  // links
  app.get('/faqs/index', FaqsController.index)
  app.post('/faqs/post', FaqsController.post)
  app.put('/faqs/update', FaqsController.update)
  app.delete('/faqs/manyDelete', FaqsController.manyDestroy)
  // address
  app.get('/address/index', AddressController.index)
  app.get('/address/SiteRequest', AddressController.SiteRequest)
  app.post('/address/post', AddressController.post)
  app.put('/address/update', AddressController.update)
  app.delete('/address/manyDelete', AddressController.manyDestroy)
  // menu
  app.get('/menu/index', MenuController.index)
  app.get('/menu/cascadeList', MenuController.cascadeList)
  app.get('/menu/findById', MenuController.findById)
  app.post('/menu/post', MenuController.post)
  app.put('/menu/update', MenuController.update)
  app.delete('/menu/manyDelete', MenuController.manyDestroy)
  app.delete('/menu/manyDeletehelpMenu', MenuController.manyDestroyhelpMenu)
  // sideMenu
  app.get('/sideMenu/index', SideMenuController.index)
  app.post('/sideMenu/post', SideMenuController.post)
  app.put('/sideMenu/update', SideMenuController.update)
  app.delete('/sideMenu/manyDelete', SideMenuController.manyDestroy)
  // Content
  app.get('/content/index', ContentController.index)
  app.get('/content/indexAdmin', ContentController.indexAdmin)
  app.get('/content/getContentById', ContentController.getContentById)
  app.get('/content/incrementCount', ContentController.incrementCount)
  app.post('/content/post', ContentController.post)
  app.put('/content/update', ContentController.update)
  app.put('/content/updateSpecial', ContentController.updateSpecial)
  app.put('/content/updateStopPress', ContentController.updateStopPress)
  app.delete('/content/manyDelete', ContentController.manyDestroy)
  app.delete('/conferenceMany/manyRemove', ContentController.manyDeActive)
  app.put('/conferenceMany/manyRestore', ContentController.manyRestore)
  // comment
  app.get('/comment/index', CommentController.index)
  app.post('/comment/post', CommentController.post)
  app.put('/comment/update', CommentController.update)
  app.delete('/comment/manyDelete', CommentController.manyDestroy)
  app.get('/comment/show', CommentController.show)
  // OnlineCount
  app.get('/onlinecount/incrementCount', OnlineCountController.incrementCount)
  app.get('/onlinecount/index', OnlineCountController.index)
  // MenusCount
  app.get('/menuscount/index', MenuCountController.index)
  app.get('/categorycount/index', CategoryCountController.index)
  app.post('/contentLayout/SiteRequest', LogController.LogRequest)
  // search
  app.get('/search/index', SearchController.index)
  app.post('/search/post', SearchController.post)

  app.get('/role/index', RoleController.index)
  app.post('/role/post', RoleController.post)
  app.put('/role/update', RoleController.update)
  app.delete('/role/manyDelete', RoleController.manyDestroy)
}
